package br.com.barbeirofinanceiro.persistence;

import br.com.barbeirofinanceiro.application.caixa.CaixaService;
import br.com.barbeirofinanceiro.domain.caixa.*; import br.com.barbeirofinanceiro.domain.categoria.*; import br.com.barbeirofinanceiro.domain.movimentacao.*; import br.com.barbeirofinanceiro.domain.usuario.*; import br.com.barbeirofinanceiro.domain.venda.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import java.math.BigDecimal; import java.time.*;
import static org.assertj.core.api.Assertions.assertThat;
@SpringBootTest class CaixaRealIntegrationTest extends PostgresPersistenceTest {
 @Autowired CaixaService service; @Autowired CaixaRepository caixas; @Autowired UsuarioRepository usuarios; @Autowired VendaRepository vendas; @Autowired VendaPagamentoRepository pagamentos; @Autowired MovimentacaoRepository movimentacoes; @Autowired CategoriaRepository categorias;
 Usuario usuario; Caixa caixa; Categoria categoria;
 @BeforeEach void setup(){usuario=newEntity(Usuario.class);usuario.setNome("Caixa");usuario.setEmail("caixa-real@teste.local");usuario.setSenhaHash("hash");usuarios.saveAndFlush(usuario);caixa=new Caixa();caixa.setDataCaixa(LocalDate.now());caixa.setValorInicial(BigDecimal.valueOf(100));caixa.setStatus(StatusCaixa.ABERTO);caixa.setUsuarioAbertura(usuario);caixas.saveAndFlush(caixa);categoria=newEntity(Categoria.class);categoria.setNome("Despesa");categoria.setTipo(TipoCategoria.DESPESA);categorias.saveAndFlush(categoria);}
 @AfterEach void cleanup(){pagamentos.deleteAll();vendas.deleteAll();movimentacoes.deleteAll();caixas.deleteAll();categorias.deleteAll();usuarios.deleteAll();}
 @Test void caixaSemOperacoesTemValorInicialComoEsperado(){assertThat(service.valorEsperado(service.atual())).isEqualByComparingTo("100");assertThat(service.entradasDinheiro(caixa)).isEqualByComparingTo("0");assertThat(service.saidasDinheiro(caixa)).isEqualByComparingTo("0");}
 @Test void somenteDinheiroDeVendaFinalizadaEDespesaDinheiroAfetamEsperado(){Venda v=new Venda();v.setCaixa(caixa);v.setDataVenda(LocalDate.now());v.setValorTotal(BigDecimal.valueOf(70));vendas.saveAndFlush(v);VendaPagamento p=new VendaPagamento();p.setVenda(v);p.setFormaPagamento(FormaPagamento.DINHEIRO);p.setValor(BigDecimal.valueOf(70));pagamentos.saveAndFlush(p);Movimentacao m=new Movimentacao();m.setTipo(TipoMovimentacao.DESPESA);m.setOrigem(OrigemMovimentacao.MANUAL);m.setDescricao("Compra");m.setValor(BigDecimal.valueOf(20));m.setDataMovimentacao(LocalDate.now());m.setCategoria(categoria);m.setFormaPagamento(FormaPagamento.DINHEIRO);m.setCaixa(caixa);movimentacoes.saveAndFlush(m);assertThat(service.valorEsperado(service.atual())).isEqualByComparingTo("150");}
 @Test void pagamentosNaoMonetariosNaoEntramNoEsperado(){Venda v=new Venda();v.setCaixa(caixa);v.setDataVenda(LocalDate.now());v.setValorTotal(BigDecimal.valueOf(50));vendas.saveAndFlush(v);VendaPagamento p=new VendaPagamento();p.setVenda(v);p.setFormaPagamento(FormaPagamento.PIX);p.setValor(BigDecimal.valueOf(50));pagamentos.saveAndFlush(p);assertThat(service.valorEsperado(service.atual())).isEqualByComparingTo("100");}
}
