package br.com.barbeirofinanceiro.persistence;

import br.com.barbeirofinanceiro.domain.caixa.*; import br.com.barbeirofinanceiro.domain.cliente.*; import br.com.barbeirofinanceiro.domain.usuario.*; import br.com.barbeirofinanceiro.domain.venda.*;
import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.test.web.servlet.MockMvc; import java.math.BigDecimal; import java.time.LocalDate;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.user; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.get; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*;
@SpringBootTest @AutoConfigureMockMvc class ClienteRelatorioControllerIntegrationTest extends PostgresPersistenceTest {
 private static final String USER="ranking@teste.local"; @Autowired MockMvc mvc; @Autowired UsuarioRepository usuarios; @Autowired ClienteRepository clientes; @Autowired CaixaRepository caixas; @Autowired VendaRepository vendas;
 private Caixa caixa;
 @BeforeEach void setup(){Usuario u=newEntity(Usuario.class);u.setNome("Relatório");u.setEmail(USER);u.setSenhaHash("hash");usuarios.saveAndFlush(u);caixa=new Caixa();caixa.setDataCaixa(LocalDate.now());caixa.setValorInicial(BigDecimal.ZERO);caixa.setStatus(StatusCaixa.ABERTO);caixa.setUsuarioAbertura(u);caixas.saveAndFlush(caixa);}
 @AfterEach void cleanup(){vendas.deleteAll();caixas.deleteAll();clientes.deleteAll();usuarios.deleteAll();}
 @Test void deveRankearClientesPorValorEQuantidade() throws Exception {Cliente menor=cliente("Menor");Cliente maior=cliente("Maior");venda(menor,50,StatusVenda.FINALIZADA,LocalDate.of(2026,8,28));venda(maior,100,StatusVenda.FINALIZADA,LocalDate.of(2026,8,28));venda(maior,25,StatusVenda.FINALIZADA,LocalDate.of(2026,8,28));mvc.perform(get("/api/v1/relatorios/clientes").param("dataInicial","2026-08-01").param("dataFinal","2026-08-31").with(user(USER))).andExpect(status().isOk()).andExpect(jsonPath("$",org.hamcrest.Matchers.hasSize(2))).andExpect(jsonPath("$[0].nome").value("Maior")).andExpect(jsonPath("$[0].quantidadeVendas").value(2)).andExpect(jsonPath("$[0].valorTotal").value(125)).andExpect(jsonPath("$[1].nome").value("Menor"));}
 @Test void deveIgnorarCanceladasEVendasSemCliente() throws Exception {Cliente c=cliente("Cliente");venda(c,100,StatusVenda.CANCELADA,LocalDate.of(2026,8,28));venda(null,200,StatusVenda.FINALIZADA,LocalDate.of(2026,8,28));mvc.perform(get("/api/v1/relatorios/clientes").param("dataInicial","2026-08-01").param("dataFinal","2026-08-31").with(user(USER))).andExpect(status().isOk()).andExpect(jsonPath("$").isEmpty());}
 @Test void deveRespeitarPeriodoEPermitirResultadoVazio() throws Exception {Cliente c=cliente("Fora");venda(c,100,StatusVenda.FINALIZADA,LocalDate.of(2026,7,31));mvc.perform(get("/api/v1/relatorios/clientes").param("dataInicial","2026-08-01").param("dataFinal","2026-08-31").with(user(USER))).andExpect(status().isOk()).andExpect(jsonPath("$").isEmpty());}
 @Test void deveRejeitarPeriodoInvalido() throws Exception {mvc.perform(get("/api/v1/relatorios/clientes").param("dataInicial","2026-08-31").param("dataFinal","2026-08-01").with(user(USER))).andExpect(status().isBadRequest()).andExpect(jsonPath("$.message").value("A data inicial não pode ser posterior à data final"));}
 private Cliente cliente(String nome){Cliente c=new Cliente();c.setNome(nome);return clientes.saveAndFlush(c);}
 private void venda(Cliente c,int valor,StatusVenda status,LocalDate data){Venda v=new Venda();v.setCliente(c);v.setCaixa(caixa);v.setDataVenda(data);v.setValorTotal(BigDecimal.valueOf(valor));v.setStatus(status);vendas.saveAndFlush(v);}
}
