package br.com.barbeirofinanceiro.persistence;

import br.com.barbeirofinanceiro.domain.caixa.*; import br.com.barbeirofinanceiro.domain.categoria.*; import br.com.barbeirofinanceiro.domain.despesarecorrente.*; import br.com.barbeirofinanceiro.domain.movimentacao.*; import br.com.barbeirofinanceiro.domain.usuario.*;
import tools.jackson.databind.ObjectMapper; import org.junit.jupiter.api.*; import org.springframework.beans.factory.annotation.Autowired; import org.springframework.boot.test.context.SpringBootTest; import org.springframework.boot.webmvc.test.autoconfigure.AutoConfigureMockMvc; import org.springframework.http.MediaType; import org.springframework.test.web.servlet.*; import java.math.BigDecimal; import java.time.*; import java.util.*;
import static org.springframework.security.test.web.servlet.request.SecurityMockMvcRequestPostProcessors.*; import static org.springframework.test.web.servlet.request.MockMvcRequestBuilders.*; import static org.springframework.test.web.servlet.result.MockMvcResultMatchers.*; import static org.assertj.core.api.Assertions.assertThat;
@SpringBootTest @AutoConfigureMockMvc class DespesaControllerIntegrationTest extends PostgresPersistenceTest {
 private static final String USER="despesa-user@teste.local"; @Autowired MockMvc mvc; @Autowired ObjectMapper mapper; @Autowired CategoriaRepository cats; @Autowired MovimentacaoRepository movs; @Autowired DespesaRecorrenteRepository recs; @Autowired CaixaRepository caixas; @Autowired UsuarioRepository users;
 private UUID despesa, receita; private Usuario usuario;
 @BeforeEach void setup(){usuario=newEntity(Usuario.class);usuario.setNome("Usuário");usuario.setEmail(USER);usuario.setSenhaHash("hash");users.saveAndFlush(usuario);Categoria c=newEntity(Categoria.class);c.setNome("Operacional");c.setTipo(TipoCategoria.DESPESA);despesa=cats.saveAndFlush(c).getId();Categoria r=newEntity(Categoria.class);r.setNome("Receitas");r.setTipo(TipoCategoria.RECEITA);receita=cats.saveAndFlush(r).getId();Caixa caixa=new Caixa();caixa.setDataCaixa(LocalDate.now());caixa.setValorInicial(BigDecimal.TEN);caixa.setStatus(StatusCaixa.ABERTO);caixa.setUsuarioAbertura(usuario);caixas.saveAndFlush(caixa);}
 @AfterEach void cleanup(){recs.deleteAll();movs.deleteAll();caixas.deleteAll();cats.deleteAll();users.deleteAll();}
 @Test void deveCriarDespesaDinheiroAssociadaAoCaixa() throws Exception {mvc.perform(post("/api/v1/movimentacoes").with(csrf()).with(user(USER)).contentType(MediaType.APPLICATION_JSON).content(req("150",despesa,"DINHEIRO"))).andExpect(status().isCreated()).andExpect(jsonPath("$.caixaId").isNotEmpty()).andExpect(jsonPath("$.formaPagamento").value("DINHEIRO"));}
 @Test void deveCriarDespesaSemCaixaParaPix() throws Exception {fecharCaixa();mvc.perform(post("/api/v1/movimentacoes").with(csrf()).with(user(USER)).contentType(MediaType.APPLICATION_JSON).content(req("20",despesa,"PIX"))).andExpect(status().isCreated()).andExpect(jsonPath("$.caixaId").doesNotExist());}
 @Test void deveRejeitarValorDescricaoECategoriaDeReceita() throws Exception {criar("{\"descricao\":\"x\",\"valor\":0,\"dataMovimentacao\":\"2026-08-28\",\"categoriaId\":\""+despesa+"\",\"formaPagamento\":\"PIX\"}",400);criar("{\"descricao\":\"   \",\"valor\":10,\"dataMovimentacao\":\"2026-08-28\",\"categoriaId\":\""+despesa+"\",\"formaPagamento\":\"PIX\"}",400);criar(req("10",receita,"PIX"),400);}
 @Test void deveFiltrarApenasDespesas() throws Exception {criar(req("10",despesa,"PIX"),201);mvc.perform(get("/api/v1/movimentacoes").param("formaPagamento","PIX").with(user(USER))).andExpect(status().isOk()).andExpect(jsonPath("$",org.hamcrest.Matchers.hasSize(1)));}
 @Test void deveCriarAtualizarEInativarRecorrente() throws Exception {String b=recBody();MvcResult r=mvc.perform(post("/api/v1/despesas-recorrentes").with(csrf()).with(user(USER)).contentType(MediaType.APPLICATION_JSON).content(b)).andExpect(status().isCreated()).andReturn();UUID id=UUID.fromString(mapper.readTree(r.getResponse().getContentAsString()).get("id").asText());mvc.perform(put("/api/v1/despesas-recorrentes/{id}",id).with(csrf()).with(user(USER)).contentType(MediaType.APPLICATION_JSON).content(b.replace("100","120"))).andExpect(status().isOk()).andExpect(jsonPath("$.valor").value(120));mvc.perform(patch("/api/v1/despesas-recorrentes/{id}/inativar",id).with(csrf()).with(user(USER))).andExpect(status().isOk()).andExpect(jsonPath("$.ativa").value(false));}
 @Test void deveRejeitarRecorrenteInvalida() throws Exception {String b=recBody().replace("\"diaVencimento\":10","\"diaVencimento\":32");criarRec(b,400);criarRec(recBody().replace("\"dataInicio\":\"2026-08-28\"","\"dataInicio\":\"2026-08-29\",\"dataFim\":\"2026-08-28\""),400);}
 private String req(String valor,UUID cat,String forma){return "{\"descricao\":\"Compra\",\"valor\":"+valor+",\"dataMovimentacao\":\"2026-08-28\",\"categoriaId\":\""+cat+"\",\"formaPagamento\":\""+forma+"\"}";}
 private void criar(String json,int code)throws Exception{mvc.perform(post("/api/v1/movimentacoes").with(csrf()).with(user(USER)).contentType(MediaType.APPLICATION_JSON).content(json)).andExpect(status().is(code));}
 private String recBody(){return "{\"descricao\":\"Aluguel\",\"valor\":100,\"categoriaId\":\""+despesa+"\",\"diaVencimento\":10,\"periodicidade\":\"MENSAL\",\"formaPagamento\":\"DINHEIRO\",\"dataInicio\":\"2026-08-28\"}";}
 private void criarRec(String json,int code)throws Exception{mvc.perform(post("/api/v1/despesas-recorrentes").with(csrf()).with(user(USER)).contentType(MediaType.APPLICATION_JSON).content(json)).andExpect(status().is(code));}
 private void fecharCaixa(){Caixa c=caixas.findFirstByStatusOrderByDataCaixaDesc(StatusCaixa.ABERTO).get();c.setStatus(StatusCaixa.FECHADO);c.setValorApurado(BigDecimal.TEN);c.setDiferenca(BigDecimal.ZERO);c.setUsuarioFechamento(usuario);c.setFechadoEm(Instant.now());caixas.saveAndFlush(c);}
}
