package br.com.barbeirofinanceiro.application.despesa;
import br.com.barbeirofinanceiro.domain.caixa.*; import br.com.barbeirofinanceiro.domain.categoria.*; import br.com.barbeirofinanceiro.domain.despesarecorrente.*; import br.com.barbeirofinanceiro.domain.movimentacao.*;
import org.springframework.data.domain.*; import org.springframework.data.jpa.domain.Specification; import org.springframework.stereotype.Service; import org.springframework.transaction.annotation.Transactional;
import java.time.*; import java.util.*;
@Service public class DespesaService {
 private final MovimentacaoRepository movimentacoes; private final DespesaRecorrenteRepository recorrentes; private final CategoriaRepository categorias; private final CaixaRepository caixas;
 public DespesaService(MovimentacaoRepository m,DespesaRecorrenteRepository r,CategoriaRepository c,CaixaRepository x){movimentacoes=m;recorrentes=r;categorias=c;caixas=x;}
 @Transactional public Movimentacao criar(CriarMovimentacaoRequest r){Categoria c=categoria(r.categoriaId()); Movimentacao m=new Movimentacao(); m.setTipo(TipoMovimentacao.DESPESA);m.setOrigem(OrigemMovimentacao.MANUAL);m.setDescricao(r.descricao().trim());m.setValor(r.valor());m.setDataMovimentacao(r.dataMovimentacao());m.setCategoria(c);m.setFormaPagamento(r.formaPagamento());m.setObservacao(r.observacao()); if(r.formaPagamento()==FormaPagamento.DINHEIRO) caixas.findOpenForUpdate().ifPresent(m::setCaixa); return movimentacoes.saveAndFlush(m);}
 @Transactional(readOnly=true) public Movimentacao buscar(UUID id){return movimentacoes.findById(id).filter(m->m.getTipo()==TipoMovimentacao.DESPESA).orElseThrow(()->new DespesaNotFoundException("Despesa não encontrada"));}
 @Transactional(readOnly=true) public List<Movimentacao> listar(LocalDate ini,LocalDate fim,UUID cat,FormaPagamento forma){Specification<Movimentacao>s=(r,q,b)->b.equal(r.get("tipo"),TipoMovimentacao.DESPESA);if(ini!=null)s=s.and((r,q,b)->b.greaterThanOrEqualTo(r.get("dataMovimentacao"),ini));if(fim!=null)s=s.and((r,q,b)->b.lessThanOrEqualTo(r.get("dataMovimentacao"),fim));if(cat!=null)s=s.and((r,q,b)->b.equal(r.get("categoria").get("id"),cat));if(forma!=null)s=s.and((r,q,b)->b.equal(r.get("formaPagamento"),forma));return movimentacoes.findAll(s,Sort.by(Sort.Direction.DESC,"dataMovimentacao","createdAt"));}
 @Transactional public DespesaRecorrente criarRec(CriarDespesaRecorrenteRequest r){validarRec(r);DespesaRecorrente d=new DespesaRecorrente(); preencher(d,r);return recorrentes.saveAndFlush(d);}
 @Transactional(readOnly=true) public List<DespesaRecorrente> listarRec(){return recorrentes.findAll(Sort.by(Sort.Direction.ASC,"descricao"));}
 @Transactional(readOnly=true) public DespesaRecorrente buscarRec(UUID id){return recorrentes.findById(id).orElseThrow(()->new DespesaNotFoundException("Despesa recorrente não encontrada"));}
 @Transactional public DespesaRecorrente atualizarRec(UUID id,CriarDespesaRecorrenteRequest r){validarRec(r);DespesaRecorrente d=buscarRec(id);preencher(d,r);return recorrentes.saveAndFlush(d);}
 @Transactional public DespesaRecorrente ativo(UUID id,boolean a){DespesaRecorrente d=buscarRec(id);d.setAtiva(a);return recorrentes.saveAndFlush(d);}
 private Categoria categoria(UUID id){Categoria c=categorias.findById(id).orElseThrow(()->new DespesaNotFoundException("Categoria não encontrada"));if(c.getTipo()!=TipoCategoria.DESPESA)throw new DespesaValidationException("Categoria deve ser do tipo DESPESA");return c;}
 private void validarRec(CriarDespesaRecorrenteRequest r){if(r.diaVencimento()==null||r.diaVencimento()<1||r.diaVencimento()>31)throw new DespesaValidationException("diaVencimento deve estar entre 1 e 31");if(r.dataFim()!=null&&r.dataFim().isBefore(r.dataInicio()))throw new DespesaValidationException("dataFim não pode ser anterior à dataInicio");if(r.periodicidade()!=Periodicidade.MENSAL)throw new DespesaValidationException("Periodicidade deve ser MENSAL");categoria(r.categoriaId());}
 private void preencher(DespesaRecorrente d,CriarDespesaRecorrenteRequest r){d.setDescricao(r.descricao().trim());d.setValor(r.valor());d.setCategoria(categoria(r.categoriaId()));d.setDiaVencimento(r.diaVencimento());d.setPeriodicidade(r.periodicidade());d.setFormaPagamento(r.formaPagamento());d.setDataInicio(r.dataInicio());d.setDataFim(r.dataFim());}
}
